name: auto_tag
on:
  push:
    branches:
      - main

jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Tag Count
        id: tag_count
        run: |
          TAG_COUNT=$(git tag -l ${{github.run_id}}.* | grep -oP '\d+$' | sort -n | tail -n 1)
          echo "TAG_COUNT=$TAG_COUNT" >> $GITHUB_ENV

      - name: Calculate Revision
        id: calculate_revision
        run: |
          TAG_COUNT=$TAG_COUNT
          REVISION=$((TAG_COUNT + 1))
          echo "REVISION=$REVISION" >> $GITHUB_ENV

      - name: Create and Push Tag
        run: |
          new_tag="${{github.run_id}}.$REVISION"
          git tag $new_tag
          git push origin $new_tag
