name: Automated Tagging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bump tag
      id: bump_tag
      run: |
        TAG_PREFIX=$(date +"%d-%m-%Y")
        LAST_TAG=$(git tag --list "$TAG_PREFIX.*" --sort=-v:refname | head -n 1)

        if [[ -z "$LAST_TAG" ]]; then
          echo "No previous tag found for today"
          NEW_TAG="$TAG_PREFIX.1"
        else
          echo "Last tag is $LAST_TAG"
          LAST_TAG_SUFFIX=${LAST_TAG##*.}
          NEW_TAG="$TAG_PREFIX.$((LAST_TAG_SUFFIX + 1))"
        fi

        echo "New tag will be $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Push tag
      run: |
        git config --global user.email "68manoranjanmohanty@gmail.com"
        git config --global user.name "AshutoshM49"
        git tag ${{ env.NEW_TAG }}
        git push https://${{secrets.GH_PAT}}@github.com/AshutoshM10/React-Calculator.git $new_tag

